/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Componentes;
import clases.Frames;
import clases.Globales;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author mcsmo
 */
public final class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    HabDisp p1 = new HabDisp();
    RegHues p2 = new RegHues();
    Reservas p3 = new Reservas();
    
    public Dashboard() {
        initComponents();
        AsignarNombres();
        this.setExtendedState(Dashboard.MAXIMIZED_BOTH);
        setTitle(Globales.nombreSistema);
        setIconImage(new ImageIcon(getClass().getResource("/images/selloHotel.png")).getImage());
        this.setLocationRelativeTo(null);
        showPanel(p1);
        btnHabiDisp.setEnabled(false);
    }

    private void showPanel(JPanel p) {
        //p.setSize(1000, 418);
        p.setSize(1550, 770);
        p.setLocation(0, 0);
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        panelLateral = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreHotel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnHabitaciones = new javax.swing.JButton();
        btnHospedaje = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        btnSolicitud = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        panelGeneral = new FondoPanel();
        jSeparator2 = new javax.swing.JSeparator();
        lblSaludo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnHabiDisp = new javax.swing.JButton();
        btnRegHuesp = new javax.swing.JButton();
        btnReservas = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(6);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelLateral.setBackground(new java.awt.Color(51, 51, 51));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selloHotel64.png"))); // NOI18N
        jPanel4.add(jLabel1);

        jLabel2.setText("       ");
        jPanel4.add(jLabel2);

        txtNombreHotel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtNombreHotel.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreHotel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombreHotel.setText("jLabel2");
        jPanel4.add(txtNombreHotel);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jSeparator1.setBackground(new java.awt.Color(22, 22, 22));
        jSeparator1.setForeground(new java.awt.Color(22, 22, 22));

        btnHabitaciones.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Habitacion.png"))); // NOI18N
        btnHabitaciones.setText("jButton1");
        btnHabitaciones.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        btnHabitaciones.setBorderPainted(false);
        btnHabitaciones.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnHabitaciones.setDefaultCapable(false);
        btnHabitaciones.setMaximumSize(new java.awt.Dimension(170, 80));
        btnHabitaciones.setMinimumSize(new java.awt.Dimension(170, 80));
        btnHabitaciones.setPreferredSize(new java.awt.Dimension(170, 80));
        btnHabitaciones.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abrir.png"))); // NOI18N
        btnHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitacionesActionPerformed(evt);
            }
        });

        btnHospedaje.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnHospedaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/huesped.png"))); // NOI18N
        btnHospedaje.setText("jButton1");
        btnHospedaje.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        btnHospedaje.setBorderPainted(false);
        btnHospedaje.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnHospedaje.setDefaultCapable(false);
        btnHospedaje.setMaximumSize(new java.awt.Dimension(170, 80));
        btnHospedaje.setMinimumSize(new java.awt.Dimension(170, 80));
        btnHospedaje.setPreferredSize(new java.awt.Dimension(170, 80));
        btnHospedaje.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abrir.png"))); // NOI18N
        btnHospedaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospedajeActionPerformed(evt);
            }
        });

        btnEmpleado.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RH.png"))); // NOI18N
        btnEmpleado.setText("jButton1");
        btnEmpleado.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        btnEmpleado.setBorderPainted(false);
        btnEmpleado.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnEmpleado.setDefaultCapable(false);
        btnEmpleado.setMaximumSize(new java.awt.Dimension(170, 80));
        btnEmpleado.setMinimumSize(new java.awt.Dimension(170, 80));
        btnEmpleado.setPreferredSize(new java.awt.Dimension(170, 80));
        btnEmpleado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abrir.png"))); // NOI18N
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });

        btnSolicitud.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mantenimiento.png"))); // NOI18N
        btnSolicitud.setText("jButton1");
        btnSolicitud.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        btnSolicitud.setBorderPainted(false);
        btnSolicitud.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnSolicitud.setDefaultCapable(false);
        btnSolicitud.setMaximumSize(new java.awt.Dimension(170, 80));
        btnSolicitud.setMinimumSize(new java.awt.Dimension(170, 80));
        btnSolicitud.setPreferredSize(new java.awt.Dimension(170, 80));
        btnSolicitud.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abrir.png"))); // NOI18N
        btnSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrarSesion.png"))); // NOI18N
        btnExit.setText("    Cerrar Sesión");
        btnExit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        btnExit.setBorderPainted(false);
        btnExit.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnExit.setDefaultCapable(false);
        btnExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHospedaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnHospedaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelGeneral.setBackground(new java.awt.Color(255, 255, 255));

        lblSaludo.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        lblSaludo.setForeground(new java.awt.Color(0, 51, 102));
        lblSaludo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaludo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hola.png"))); // NOI18N
        lblSaludo.setText("jLabel3");

        lblFecha.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("jLabel4");

        lblHora.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        lblHora.setForeground(new java.awt.Color(0, 0, 0));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("jLabel3");

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        btnHabiDisp.setBackground(new java.awt.Color(0, 102, 153));
        btnHabiDisp.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnHabiDisp.setForeground(new java.awt.Color(255, 255, 255));
        btnHabiDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/habDisp.png"))); // NOI18N
        btnHabiDisp.setText("jButton1");
        btnHabiDisp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        btnHabiDisp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abrir2.png"))); // NOI18N
        btnHabiDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabiDispActionPerformed(evt);
            }
        });
        jPanel6.add(btnHabiDisp);

        btnRegHuesp.setBackground(new java.awt.Color(0, 102, 153));
        btnRegHuesp.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnRegHuesp.setForeground(new java.awt.Color(255, 255, 255));
        btnRegHuesp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registrarHuesped.png"))); // NOI18N
        btnRegHuesp.setText("jButton2");
        btnRegHuesp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        btnRegHuesp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abrir2.png"))); // NOI18N
        btnRegHuesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegHuespActionPerformed(evt);
            }
        });
        jPanel6.add(btnRegHuesp);

        btnReservas.setBackground(new java.awt.Color(0, 102, 153));
        btnReservas.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnReservas.setForeground(new java.awt.Color(255, 255, 255));
        btnReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reservacion.png"))); // NOI18N
        btnReservas.setText("jButton3");
        btnReservas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        btnReservas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abrir2.png"))); // NOI18N
        btnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasActionPerformed(evt);
            }
        });
        jPanel6.add(btnReservas);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addComponent(lblSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSaludo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHabiDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabiDispActionPerformed
        showPanel(p1);
        btnHabiDisp.setEnabled(false);
        btnRegHuesp.setEnabled(true);
        btnReservas.setEnabled(true);
    }//GEN-LAST:event_btnHabiDispActionPerformed

    private void btnRegHuespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegHuespActionPerformed
        showPanel(p2);
        btnHabiDisp.setEnabled(true);
        btnRegHuesp.setEnabled(false);
        btnReservas.setEnabled(true);
    }//GEN-LAST:event_btnRegHuespActionPerformed

    private void btnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasActionPerformed
        showPanel(p3);
        btnHabiDisp.setEnabled(true);
        btnRegHuesp.setEnabled(true);
        btnReservas.setEnabled(false);
    }//GEN-LAST:event_btnReservasActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       Frames.CerrarSesion();
       this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitacionesActionPerformed
        Habitaciones habitaciones = new Habitaciones(this,true);
        habitaciones.setVisible(true);
    }//GEN-LAST:event_btnHabitacionesActionPerformed

    private void btnHospedajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospedajeActionPerformed
        Huespedes huespedes = new Huespedes(this,true);
        huespedes.setVisible(true);
    }//GEN-LAST:event_btnHospedajeActionPerformed

    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed
        SeleccionEmpleados empleados = new SeleccionEmpleados(this,true);
        empleados.setVisible(true);
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    private void btnSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudActionPerformed
        Solicitudes solicitudes = new Solicitudes(this, true);
        solicitudes.setVisible(true);
    }//GEN-LAST:event_btnSolicitudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHabiDisp;
    private javax.swing.JButton btnHabitaciones;
    private javax.swing.JButton btnHospedaje;
    private javax.swing.JButton btnRegHuesp;
    private javax.swing.JButton btnReservas;
    private javax.swing.JButton btnSolicitud;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblSaludo;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JLabel txtNombreHotel;
    // End of variables declaration//GEN-END:variables

    public void AsignarNombres() {
        txtNombreHotel.setText(Globales.nombreHotel);
        btnHabitaciones.setText(Globales.gestionHab);
        btnHospedaje.setText(Globales.RegistroHosp);
        btnSolicitud.setText(Globales.SolicitudMant);
        btnEmpleado.setText(Globales.RegistroEmp);
        btnExit.setText(Globales.CerrarSesion);
        lblSaludo.setText(Globales.nombreUsuario + "Marcelo");
        lblFecha.setText("Fecha: " + Componentes.FechaActual());
        lblHora.setText(Componentes.HoraActual());
        btnHabiDisp.setText(Globales.HabDisp);
        btnRegHuesp.setText(Globales.RegHues);
        btnReservas.setText(Globales.Reservaciones);
    }

    class FondoPanel extends JPanel {

        private Image img;

        @Override
        public void paint(Graphics g) {
            img = new ImageIcon(getClass().getResource("/images/fondo_panel.jpg")).getImage();
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
